export const DOMAIN_CLIENT = "3dtour";
// const DOMAIN = "https://3dtour.io.vn/app/api"; // product
// export const AFTER_DOMAIN = "3dtour.io.vn/app"; // product
export const AFTER_DOMAIN = "localhost:8080/app"; // dev
const DOMAIN = "http://localhost:8080/app/api"; // dev
export const DEFAULT_AVATAR =
  "https://res.cloudinary.com/dkoc6kbg1/image/upload/v1749780602/fxa5ft9aesxkfiskamne.jpg";

export const API_URLS = {
  BASE: `${DOMAIN}`,
  LOGIN: `${DOMAIN}/login`,
  LOGIN_BY_GOOGLE: `${DOMAIN}/login/google`,
  LOGOUT: `${DOMAIN}/authenticate/logout`,
  REGISTER: `${DOMAIN}/register`,
  CREATE_ADMIN: `${DOMAIN}/register/createAdmin`,
  USER: `${DOMAIN}/user`,
  VERIFY: `${DOMAIN}/authenticate/verifyEmail`,
  REFRESH_TOKEN: `${DOMAIN}/authenticate/refresh`,
  FORGOT_PASSWORD: `${DOMAIN}/user/forgotPassword`,
  CHANGE_PROFILE: `${DOMAIN}/user/updateProfile`,
  CHANGE_PASSWORD: `${DOMAIN}/user/updatePassword`,
  CHANGE_AVATAR: `${DOMAIN}/user/updateAvatar`,
  CHANGE_NODE_STATUS: `${DOMAIN}/node/changeStatus`,
  REMOVE_NODE: `${DOMAIN}/node/remove`,

  UPLOAD_CLOUD: `${DOMAIN}/v1/admin/cloud/upload`,

  GET_MASTER_NODES: `${DOMAIN}/node/master`,
  GET_FEEDBACK_BY_NODE_ID: `${DOMAIN}/feedback/byId`,
  GET_ALL_MODEL: `${DOMAIN}/v1/admin/hotspot/getAllModel`,
  INCREASE_NUM_DOWNLOAD_MODEL: `${DOMAIN}/v1/admin/hotspot/countDownloadModel`,
  GET_ALL_SPACES: `${DOMAIN}/space`,
  GET_ALL_FIELDS: `${DOMAIN}/field`,
  INCREASE_NODE_VIEW: `${DOMAIN}/node/increaseView`,
  GET_PRELOAD_NODES: `${DOMAIN}/node/preloadNodeList`,
  GET_FULL_TOUR: `${DOMAIN}/node/nodeListByMasterId`,
  GET_DEFAULT_NODE: `${DOMAIN}/node/default`,
  PRIVATE_NODE_OF_USER: `${DOMAIN}/node/privateByUser`,
  FAIL_NODE_OF_USER: `${DOMAIN}/node/failByUser`,
  NODE_OF_USER: `${DOMAIN}/node/byUser`,
  NODE_BY_ID: `${DOMAIN}/node/byId`,
  NUM_VIEW_OF_USER: `${DOMAIN}/node/getNumOfUser`,
  COMMENT_OF_NODE: `${DOMAIN}/comment/getOfNode`,
  NUM_COMMENT_OF_USER: `${DOMAIN}/comment/getNumOfUser`,
  NUM_DOWNLOAD_MODEL_OF_USER: `${DOMAIN}/v1/admin/hotspot/getNumDownloadModel`,
  SEND_COMMENT: `${DOMAIN}/comment/send`,
  EDIT_COMMENT: `${DOMAIN}/comment/update`,
  REMOVE_COMMENT: `${DOMAIN}/comment/remove`,

  SEND_CONTACT: `${DOMAIN}/contact/send`,
  ADMIN_FEEDBACK_CONTACT: `${DOMAIN}/v1/admin/contact/feedback`,
  ADMIN_APPROVE_TOUR: `${DOMAIN}/v1/admin/approveTour`,

  SEARCH_FIELDS: `${DOMAIN}/admin/field/search`,
  SEARCH_SPACES: `${DOMAIN}/admin/space/search`,
  SEARCH_NODES: `${DOMAIN}/v1/admin/node/search`,
  SEARCH_AUTO_NODES: `${DOMAIN}/v1/admin/node/searchAutoNode`,
  SEARCH_ICONS: `${DOMAIN}/v1/admin/icon/search`,

  GET_MODEL: `${DOMAIN}/v1/admin/hotspot/getModel`,
  GET_NUM_TOTAL_MODEL: `${DOMAIN}/v1/admin/hotspot/getNumTotalModel`,
  ADMIN_GET_DASHBOARD: `${DOMAIN}/admin/dashboard`,
  ADMIN_GET_ALL_NODES: `${DOMAIN}/v1/admin/node`,
  ADMIN_GET_NODES_BY_PAGE: `${DOMAIN}/v1/admin/node/byPage`,
  ADMIN_GET_AUTO_TOURS: `${DOMAIN}/v1/admin/node/getAutoTour`,
  GET_AUTO_TOURS: `${DOMAIN}/node/getAutoTour`,
  ADMIN_GET_MASTER_NODES_OF_SPACE: `${DOMAIN}/v1/admin/node/masterNodeList`,
  ADMIN_GET_ALL_SPACES: `${DOMAIN}/admin/space`,
  ADMIN_GET_SPACES_BY_PAGE: `${DOMAIN}/admin/space/byPage`,
  ADMIN_GET_SPACE_BY_ID: `${DOMAIN}/admin/space/byId`,
  ADMIN_GET_SPACE_OF_FIELD: `${DOMAIN}/admin/space/byField`,
  ADMIN_GET_ALL_ICONS: `${DOMAIN}/v1/admin/icon`,
  ADMIN_GET_HOTSPOT_TYPES: `${DOMAIN}/admin/hotspotType`,
  ADMIN_GET_ALL_FIELDS: `${DOMAIN}/admin/field`,
  ADMIN_GET_FIELDS_BY_PAGE: `${DOMAIN}/admin/field/byPage`,
  ADMIN_GET_ALL_NODE_IMAGES: `${DOMAIN}/v1/admin/node/getNodeImg`,
  ADMIN_GET_ALL_CONTACTS: `${DOMAIN}/v1/admin/contact/getAll`,
  ADMIN_GET_FEEDBACK: `${DOMAIN}/v1/admin/feedback/getAll`,

  ADMIN_CREATE_NODES: `${DOMAIN}/v1/admin/node/insert`,
  ADMIN_UPDATE_NODES: `${DOMAIN}/v1/admin/node/update`,
  ADMIN_CREATE_AUTO_TOUR: `${DOMAIN}/v1/admin/node/createAutoTour`,
  ADMIN_UPDATE_AUTO_TOUR: `${DOMAIN}/v1/admin/node/updateAutoTour`,
  ADMIN_LINK_NODES: `${DOMAIN}/v1/admin/node/linkNode`,
  ADMIN_CREATE_FIELDS: `${DOMAIN}/admin/field/create`,
  ADMIN_CREATE_SPACES: `${DOMAIN}/admin/space/create`,
  ADMIN_CREATE_ICONS: `${DOMAIN}/v1/admin/icon/`,
  ADMIN_CHANGE_THUMBNAIL_ICONS: `${DOMAIN}/v1/admin/icon/changeThumbnail`,

  ADMIN_ATTACH_SPACE_LOCATION: `${DOMAIN}/admin/space/attachLocation`,
  ADMIN_REMOVE_SPACE_LOCATION: `${DOMAIN}/admin/space/removeLocation`,
  ADMIN_UPDATE_SPACE_BY_ID: `${DOMAIN}/admin/space`,
  ADMIN_UPDATE_OVERVIEW_TOUR_BY_MASTERID: `${DOMAIN}/v1/admin/node`,

  ADMIN_CHANGE_FIELD_STATUS: `${DOMAIN}/admin/field/changeStatus`,
  ADMIN_CHANGE_SPACE_STATUS: `${DOMAIN}/admin/space/changeStatus`,
  ADMIN_CHANGE_NODE_STATUS: `${DOMAIN}/v1/admin/node/changeStatus`,
  ADMIN_CHANGE_TOUR_BY_ID: `${DOMAIN}/v1/admin/node`,
  ADMIN_CHANGE_MASTER_SPACE: `${DOMAIN}/admin/space/setMasterSpace`,
  ADMIN_CHANGE_NAME_SPACE: `${DOMAIN}/admin/space/changeName`,
  ADMIN_CHANGE_MASTER_NODE_BY_ID: `${DOMAIN}/admin/space/setMasterNodeById`,
  ADMIN_CHANGE_NAME_FIELD: `${DOMAIN}/admin/field/changeName`,
  ADMIN_CHANGE_ICON_STATUS: `${DOMAIN}/v1/admin/icon/changeStatus`,
  ADMIN_CHANGE_NAME_ICON: `${DOMAIN}/v1/admin/icon/changeName`,
};
